### ISSUE TITLE
Adding a new label resets all label-positions

### ISSUE THREAD

**Issue by jLouzado** [aman-maharshi/user-focus-test-problem#1]
# Steps

- load page
- move `HTML` tag to Box-1
- Add a new Label

# Observation

- All four labels are now in the top-area

# Expectation

- `HTML` should stay in Box-1, 
- new label gets added to the top-area

# Reproducibility

- Always

**Comment by aman-maharshi** [comment]
Hi Joel, thanks for reaching out

I've fixed the Issue now

Let me know in case any other changes are required
